### ISSUE TITLE
Simple strategy description

### ISSUE THREAD

**Issue by jokaorgua** [jeka-kiselyov/kramjah#1]
Hello. Could you please describe in simple words how does the Simple.js strategy work? I wasn't able to understand the logic. Thanks

**Comment by jeka-kiselyov** [comment]
@jokaorgua basically what it does is simple stupid scalping. It fills price iterval down from current point with MarketTraderBidWorker.js(instance that buy piece of crypto, sells it when price go up and then buy again when price go down after) buy bids. Other than this, there're few checks for balancing spendings and avoiding buying on local tops.

Don't expect any magic from it, Simple strategy makes profit less than hodl when crypto rasing(though you are also losing less than hodl if it goes down). Feel free to modify it with your trading ideas and run with 'flashback' command to estimate it on historical prices.
