### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by cooliobr** [jeka-kiselyov/kramjah#2]
Hi, i got this message when i try to start bot

info: wss://api.demo.hitbtc.com/api/3/ws/trading Initializing WebSocket connection...
info: wss://api.demo.hitbtc.com/api/3/ws/trading WebSocket connection opened
info: wss://api.demo.hitbtc.com/api/3/ws/trading Authing...
info: wss://api.demo.hitbtc.com/api/3/ws/trading Sending request... login
info: wss://api.demo.hitbtc.com/api/3/ws/trading Got error code=1004, message=Unsupported authorization method, description=api_key and secret_key required
info: wss://api.demo.hitbtc.com/api/3/ws/trading Got response for:  login Took 260ms
info: wss://api.demo.hitbtc.com/api/3/ws/trading Authentication failure.
info: wss://api.demo.hitbtc.com/api/3/ws/trading Terminating...

i have created a file with .env and keys from hitbtc.

**Comment by jeka-kiselyov** [comment]
Hi @cooliobr 

Does your `.env` file has content of:

HITBTC_API_KEY=xxxxxxxxxx
HITBTC_SECRET_KEY=yyyyyyyyyyy
HITBTC_MODE=market

and placed in the root folder of application?

**Comment by cooliobr** [comment]
yes i placed at root app folder
My os is OSX 11.6 ( Big Sur )

Em qua., 20 de out. de 2021 às 12:13, Jeka Kiselyov <
***@***.***> escreveu:

**Comment by jeka-kiselyov** [comment]
@cooliobr 

You instance connects to demo hitbtc server ( the one here - https://demo.hitbtc.com/ ), means it can't read even HITBTC_MODE variable from the .env file ( it's demo by default, `if (HITBTC_MODE != 'market') HITBTC_MODE = 'demo' )

Be sure there's no extra spaces or something, maybe add extra empty line after it. And I will try to push some update with better logging today, so we can diagnose this better.

**Comment by cooliobr** [comment]
info: Getting symbol info: BTCUSD
info: API Initialization...
info: API Got symbols information 1339
info: Tick size: 0.01
info: Quantity increment: 0.00001
info: Base currency: BTC
info: Quote currency: USDT
info: Got symbol infromation from the market: btcusd
info: Restoring bids data from market...
info: wss://api.hitbtc.com/api/3/ws/trading Initializing WebSocket
connection...
info: wss://api.hitbtc.com/api/3/ws/trading WebSocket connection opened
info: wss://api.hitbtc.com/api/3/ws/trading Authing...
info: wss://api.hitbtc.com/api/3/ws/trading Sending request... login
info: wss://api.hitbtc.com/api/3/ws/trading Got error code=1004,
message=Unsupported authorization method, description=api_key and
secret_key required
info: wss://api.hitbtc.com/api/3/ws/trading Got response for:  login Took
249ms
info: wss://api.hitbtc.com/api/3/ws/trading Authentication failure.
info: wss://api.hitbtc.com/api/3/ws/trading Terminating...


same, i have tried before

Att.

Rafael Machado
HALLO! Media Group.
REGS IT LTDA.
ANTIK Business Representative BRASIL
"Believe in the future, believe in your success"
"Não existe patch para a estupidez humana"





Em qua., 20 de out. de 2021 às 13:57, Jeka Kiselyov <
***@***.***> escreveu:

**Comment by jeka-kiselyov** [comment]
@cooliobr connects to the right server now, though. Means, HITBTC_MODE variable readed Ok. Maybe check other two ( HITBTC_API_KEY and HITBTC_SECRET_KEY ) for extra spaces?

**Comment by cooliobr** [comment]
i made some changes in .js files to connect in correct server

i will try latter with linux machine





Em qua., 20 de out. de 2021 às 14:10, Jeka Kiselyov <
***@***.***> escreveu:

**Comment by jeka-kiselyov** [comment]
@cooliobr got it, I will improve logging anyway in that place.

btw, it was confirmed to work on mac (not mine though, not sure about version).

**Comment by cooliobr** [comment]
Brother, i reboot my mac , after this it work


Att.

Rafael Machado
HALLO! Media Group.
REGS IT LTDA.
ANTIK Business Representative BRASIL
"Believe in the future, believe in your success"
"Não existe patch para a estupidez humana"





Em qua., 20 de out. de 2021 às 14:33, Jeka Kiselyov <
***@***.***> escreveu:

**Comment by jeka-kiselyov** [comment]
Cool. @cooliobr 

Good luck with trading. Don't forget to be careful with trading settings.

**Comment by cooliobr** [comment]
Thanks...
You have any good strategy ?
pair SHIB-USDT or SHIB-BTC or any other.

**Comment by jeka-kiselyov** [comment]
@cooliobr actually, to start, I'd prefer something classic around eth-btc-usdt or something from top 5. Much less stress, as it's less volatile, and somehow ok to stay with coins even if price goes down too much.

But feel free to play with strategy on historical data ( with `flashback` command) on your pairs. I don't have something I can recommend to be successful on all cases.

**Comment by cooliobr** [comment]
i try for some hours and no orders make, what i do wrong ?
i put btc-usdt, can you help my with any strategy ?


Att.

Rafael Machado
HALLO! Media Group.
REGS IT LTDA.
ANTIK Business Representative BRASIL
"Believe in the future, believe in your success"
"Não existe patch para a estupidez humana"





Em qua., 20 de out. de 2021 às 16:11, Jeka Kiselyov <
***@***.***> escreveu:

**Comment by jeka-kiselyov** [comment]
Default strategy posts buy orders when price goes down.

You can comment out this lines:

```

		if (shiftsPast[0] > -0.5 || shiftsPast[1] > -0.5) {
			// do not add any buy bids if price is rising in last 2 hours
			//
			return;
		}
```

in Simple.js, and it will create buy orders right after starting
